function init(self)


end

function update(self)
	local pos = go.get_position()
	if pos.y > 640 then
		go.delete()		
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") and message.enter then
		msg.post("/enemy_Spawner_2_3#enemy_spawner_2_3", "5_Damage")
		msg.post("/enemy_Spawner#enemy_spawner", "5_Damage")
		go.delete()
		particlefx.play("#explosion")
	end
end